<?php

namespace Proxies\__CG__\MINSAL\IndicadoresBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrigenDatos extends \MINSAL\IndicadoresBundle\Entity\OrigenDatos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'nombre', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'sentenciaSql', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'conexiones', 'archivoNombre', 'file', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esFusionado', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esPivote', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fechaCorte', 'nombreCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'camposFusionados', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'ventana', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'actualizacionIncremental', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'periodicidad', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'reporteActualizaciones', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fusiones', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'campos', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'variables'];
        }

        return ['__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'nombre', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'sentenciaSql', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'conexiones', 'archivoNombre', 'file', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esFusionado', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esPivote', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fechaCorte', 'nombreCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'camposFusionados', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'ventana', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'actualizacionIncremental', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'periodicidad', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'reporteActualizaciones', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fusiones', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'campos', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'variables'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrigenDatos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function upload($basepath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', [$basepath]);

        return parent::upload($basepath);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchivoNombre($archivoNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchivoNombre', [$archivoNombre]);

        return parent::setArchivoNombre($archivoNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivoNombre', []);

        return parent::getArchivoNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentenciaSql($sentenciaSql)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentenciaSql', [$sentenciaSql]);

        return parent::setSentenciaSql($sentenciaSql);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentenciaSql()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentenciaSql', []);

        return parent::getSentenciaSql();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsFusionado($esFusionado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsFusionado', [$esFusionado]);

        return parent::setEsFusionado($esFusionado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsFusionado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsFusionado', []);

        return parent::getEsFusionado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamposFusionados($camposFusionados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamposFusionados', [$camposFusionados]);

        return parent::setCamposFusionados($camposFusionados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamposFusionados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamposFusionados', []);

        return parent::getCamposFusionados();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentana($ventana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentana', [$ventana]);

        return parent::setVentana($ventana);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentana', []);

        return parent::getVentana();
    }

    /**
     * {@inheritDoc}
     */
    public function setActualizacionIncremental($actualizacionIncremental)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActualizacionIncremental', [$actualizacionIncremental]);

        return parent::setActualizacionIncremental($actualizacionIncremental);
    }

    /**
     * {@inheritDoc}
     */
    public function getActualizacionIncremental()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualizacionIncremental', []);

        return parent::getActualizacionIncremental();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodicidad(\MINSAL\IndicadoresBundle\Entity\Periodos $periodicidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodicidad', [$periodicidad]);

        return parent::setPeriodicidad($periodicidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodicidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodicidad', []);

        return parent::getPeriodicidad();
    }

    /**
     * {@inheritDoc}
     */
    public function addReporteActualizaciones(\MINSAL\IndicadoresBundle\Entity\ReporteActualizacion $reporteActualizaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReporteActualizaciones', [$reporteActualizaciones]);

        return parent::addReporteActualizaciones($reporteActualizaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getReporteActualizaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReporteActualizaciones', []);

        return parent::getReporteActualizaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addFusione(\MINSAL\IndicadoresBundle\Entity\OrigenDatos $fusiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFusione', [$fusiones]);

        return parent::addFusione($fusiones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFusione(\MINSAL\IndicadoresBundle\Entity\OrigenDatos $fusiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFusione', [$fusiones]);

        return parent::removeFusione($fusiones);
    }

    /**
     * {@inheritDoc}
     */
    public function getFusiones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFusiones', []);

        return parent::getFusiones();
    }

    /**
     * {@inheritDoc}
     */
    public function addCampo(\MINSAL\IndicadoresBundle\Entity\Campo $campos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCampo', [$campos]);

        return parent::addCampo($campos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCampo(\MINSAL\IndicadoresBundle\Entity\Campo $campos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCampo', [$campos]);

        return parent::removeCampo($campos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampos', []);

        return parent::getCampos();
    }

    /**
     * {@inheritDoc}
     */
    public function getCamposCalculados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamposCalculados', []);

        return parent::getCamposCalculados();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllFields', []);

        return parent::getAllFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setEsCatalogo($esCatalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsCatalogo', [$esCatalogo]);

        return parent::setEsCatalogo($esCatalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsCatalogo', []);

        return parent::getEsCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCorte($fechaCorte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCorte', [$fechaCorte]);

        return parent::setFechaCorte($fechaCorte);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCorte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCorte', []);

        return parent::getFechaCorte();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCatalogo($nombreCatalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCatalogo', [$nombreCatalogo]);

        return parent::setNombreCatalogo($nombreCatalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCatalogo', []);

        return parent::getNombreCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addVariable(\MINSAL\IndicadoresBundle\Entity\VariableDato $variables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVariable', [$variables]);

        return parent::addVariable($variables);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVariable(\MINSAL\IndicadoresBundle\Entity\VariableDato $variables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVariable', [$variables]);

        return parent::removeVariable($variables);
    }

    /**
     * {@inheritDoc}
     */
    public function getVariables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariables', []);

        return parent::getVariables();
    }

    /**
     * {@inheritDoc}
     */
    public function addConexione(\MINSAL\IndicadoresBundle\Entity\Conexion $conexiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConexione', [$conexiones]);

        return parent::addConexione($conexiones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConexione(\MINSAL\IndicadoresBundle\Entity\Conexion $conexiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConexione', [$conexiones]);

        return parent::removeConexione($conexiones);
    }

    /**
     * {@inheritDoc}
     */
    public function getConexiones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConexiones', []);

        return parent::getConexiones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsPivote($esPivote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsPivote', [$esPivote]);

        return parent::setEsPivote($esPivote);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsPivote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsPivote', []);

        return parent::getEsPivote();
    }

    /**
     * {@inheritDoc}
     */
    public function addReporteActualizacione(\MINSAL\IndicadoresBundle\Entity\ReporteActualizacion $reporteActualizaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReporteActualizacione', [$reporteActualizaciones]);

        return parent::addReporteActualizacione($reporteActualizaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReporteActualizacione(\MINSAL\IndicadoresBundle\Entity\ReporteActualizacion $reporteActualizaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReporteActualizacione', [$reporteActualizaciones]);

        return parent::removeReporteActualizacione($reporteActualizaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaLectura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaLectura', []);

        return parent::getUltimaLectura();
    }

}
