<?php

namespace Proxies\__CG__\MINSAL\IndicadoresBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClasificacionTecnicai extends \MINSAL\IndicadoresBundle\Entity\ClasificacionTecnicai implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'alertas', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'codigo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'descripcionm', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'comentario', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'meta', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'tipo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'ficha', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'clasificacionTecnicam'];
        }

        return ['__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'alertas', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'codigo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'descripcionm', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'comentario', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'meta', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'tipo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'ficha', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\ClasificacionTecnicai' . "\0" . 'clasificacionTecnicam'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClasificacionTecnicai $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function addAlertas(\MINSAL\IndicadoresBundle\Entity\IndicadorAlertasseg $alertas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlertas', [$alertas]);

        return parent::addAlertas($alertas);
    }

    /**
     * {@inheritDoc}
     */
    public function addAlerta(\MINSAL\IndicadoresBundle\Entity\IndicadorAlertasseg $alertas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlerta', [$alertas]);

        return parent::addAlerta($alertas);
    }

    /**
     * {@inheritDoc}
     */
    public function setMeta($meta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeta', [$meta]);

        return parent::setMeta($meta);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeta', []);

        return parent::getMeta();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionm($descripcionm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionm', [$descripcionm]);

        return parent::setDescripcionm($descripcionm);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionm', []);

        return parent::getDescripcionm();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentario($comentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentario', [$comentario]);

        return parent::setComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentario', []);

        return parent::getComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setClasificacionTecnicam(\MINSAL\IndicadoresBundle\Entity\ClasificacionTecnicam $clasificacionTecnicam = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasificacionTecnicam', [$clasificacionTecnicam]);

        return parent::setClasificacionTecnicam($clasificacionTecnicam);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasificacionTecnicam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasificacionTecnicam', []);

        return parent::getClasificacionTecnicam();
    }

    /**
     * {@inheritDoc}
     */
    public function setFicha(\MINSAL\IndicadoresBundle\Entity\FichaTecnica $ficha = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFicha', [$ficha]);

        return parent::setFicha($ficha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFicha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFicha', []);

        return parent::getFicha();
    }

}
